### PR TITLE
Fail package in case of build error

### LINKED ISSUE #46: Test that has a build error, does not fail the junit-report
The output of a test that failed on build might be:
```
package/name/file_test.go:9: undefined: x
FAIL	package/name [build failed]
```
running the go-junit-report on that test with the flag `-set-exit-code` still returns exit code 0.

### PR DESCRIPTION
**Pull request by posener**
Fixes #46 
In case of build error, the unittest fail, but the junit-report
with the set-exit-code flag on returns status code 0.
This commit will make it return the right status code.

### CODE REVIEW

**Comment by runyontr** [comment]
Worked for me. 
 ```
user@computer:~/go/src/some/package$ go test -v | go-junit-report --set-exit-code
# some/package
./some_test.go:35: too many arguments in call to "some/package/inner".FunctionName
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="0" failures="0" time="0.000" name="some/package">
		<properties>
			<property name="go.version" value="go1.7.5"></property>
		</properties>
	</testsuite>
</testsuites>
user@computer:~/go/src/some/package$ echo $?
1
```


 it would be great to get this in.

File: parser/parser.go [hunk 1]
```diff
@@ -40,10 +41,11 @@ type Test struct {
...
 
 var (
-	regexStatus   = regexp.MustCompile(`^\s*--- (PASS|FAIL|SKIP): (.+) \((\d+\.\d+)(?: seconds|s)\)$`)
-	regexCoverage = regexp.MustCompile(`^coverage:\s+(\d+\.\d+)%\s+of\s+statements$`)
-	regexResult   = regexp.MustCompile(`^(ok|FAIL)\s+(.+)\s(\d+\.\d+)s(?:\s+coverage:\s+(\d+\.\d+)%\s+of\s+statements)?$`)
-	regexOutput   = regexp.MustCompile(`(    )*\t(.*)`)
+	regexStatus       = regexp.MustCompile(`^\s*--- (PASS|FAIL|SKIP): (.+) \((\d+\.\d+)(?: seconds|s)\)$`)
+	regexCoverage     = regexp.MustCompile(`^coverage:\s+(\d+\.\d+)%\s+of\s+statements$`)
+	regexResult       = regexp.MustCompile(`^(ok|FAIL)\s+(.+)\s(\d+\.\d+)s(?:\s+coverage:\s+(\d+\.\d+)%\s+of\s+statements)?$`)
+	regexBuildFailure = regexp.MustCompile(`^FAIL\s+(.+)\s\[build failed]$`)
```
Comment (jstemmer) [inline parser/parser.go]: This can be combined with `regexResult`. Something like this could work:
```regex
^(ok|FAIL)\s+([^ ]+)\s+(?:(\d+\.\d+)s|(\[build failed\]))(?:\s+coverage:\s+(\d+\.\d+)%\sof\sstatements)?$
```

File: parser/parser.go [hunk 2]
```diff
@@ -88,6 +93,9 @@ func Parse(r io.Reader, pkgName string) (*Report, error) {
 		} else if matches := regexResult.FindStringSubmatch(line); len(matches) == 5 {
 			if matches[4] != "" {
```
Comment (jstemmer) [inline parser/parser.go]: With the updated regex above we can now check for the string `[build failed]` here and add a failing `Test` to the `tests` slice.

File: parser/parser.go [hunk 3]
```diff
@@ -180,3 +196,12 @@ func (r *Report) Failures() int {
 
 	return count
 }
+
+func (r *Report) Failed() bool {
```
Comment (jstemmer) [inline parser/parser.go]: Remove this, let's keep using the Failures() method.

File: go-junit-report.go [hunk 4]
```diff
@@ -37,7 +37,7 @@ func main() {
 		os.Exit(1)
 	}
 
-	if setExitCode && report.Failures() > 0 {
+	if setExitCode && report.Failed() {
```
Comment (jstemmer) [inline go-junit-report.go]: Revert this. If we introduce a failing test for build errors we can keep using `Failures()`.

File: tests/13-report.xml [hunk 5]
```diff
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<testsuites>
+	<testsuite tests="0" failures="0" time="0.000" name="package/name">
```
Comment (posener) [inline tests/13-report.xml]: @jstemmer ,capturing the build output is problematic, since the build error is in the begginning of the test log. Another thing is that the build error is in the package level, and not in the testcase level.

An example for running test on 4 packages, which two of them failing will look like that:
```
# package/name/failing1
failing1/failing_test.go:15: undefined: x
# package/name/failing2
failing2/another_failing_test.go:20: undefined: y
=== RUN TestA
--- PASS: TestA (0.10 seconds)
PASS
ok  	package/name/passing1 0.005s
=== RUN TestB
--- PASS: TestB (0.10 seconds)
PASS
ok  	package/name/passing2 0.005s
FAIL	package/name/failing1 [build failed]
FAIL	package/name/failing2 [build failed]
```
For which I think that the xml should look like:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="2" failures="0" time="0.100" name="package/name/passing1">
		<properties>
			<property name="go.version" value="1.0"></property>
		</properties>
		<testcase classname="name" name="TestA" time="0.100"></testcase>
	</testsuite>
	<testsuite tests="2" failures="0" time="0.100" name="package/name/passing2">
		<properties>
			<property name="go.version" value="1.0"></property>
		</properties>
		<testcase classname="name" name="TestB" time="0.100"></testcase>
	</testsuite>
	<testsuite tests="0" failures="1" time="0.000" name="package/name/failing1">
		<properties>
			<property name="go.version" value="1.0"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="1" time="0.000" name="package/name/failing2">
		<properties>
			<property name="go.version" value="1.0"></property>
		</properties>
	</testsuite>
</testsuites>
```
What do you think?

Comment (posener) [inline tests/13-report.xml]: Actually, maybe I can capture the output, if I'll put the captured output into a map when the beginning of the file is being read. I can have a map between the package name and the error. no problems.

Comment (jstemmer) [inline tests/13-report.xml]: Yes, that XML is about what I had in mind. The testcases for the failing packages would have an additional `<failure>` element with the error message. Using a map to store the error messages for each package SGTM.

**Comment by posener** [comment]
@jste

File: parser/parser.go [hunk 6]
```diff
@@ -42,8 +42,9 @@ type Test struct {
 var (
 	regexStatus   = regexp.MustCompile(`^\s*--- (PASS|FAIL|SKIP): (.+) \((\d+\.\d+)(?: seconds|s)\)$`)
 	regexCoverage = regexp.MustCompile(`^coverage:\s+(\d+\.\d+)%\s+of\s+statements$`)
-	regexResult   = regexp.MustCompile(`^(ok|FAIL)\s+(.+)\s(\d+\.\d+)s(?:\s+coverage:\s+(\d+\.\d+)%\s+of\s+statements)?$`)
+	regexResult   = regexp.MustCompile(`^(ok|FAIL)\s+([^ ]+)\s+(?:(\d+\.\d+)s|(\[build failed]))(?:\s+coverage:\s+(\d+\.\d+)%\sof\sstatements)?$`)
 	regexOutput   = regexp.MustCompile(`(    )*\t(.*)`)
+	regexCapture  = regexp.MustCompile(`^#\s(.+)`)
```
Comment (jstemmer) [inline parser/parser.go]: There's no need for a regexp here, let's use `strings.HasPrefix(..., "# ")` instead and `strings.TrimPrefix` to get the package name.

File: parser/parser.go [hunk 7]
```diff
@@ -85,19 +92,35 @@ func Parse(r io.Reader, pkgName string) (*Report, error) {
...
 				Time:        parseTime(matches[3]),
 				Tests:       tests,
-				CoveragePct: coveragePct,
-			})
+			}
+
+			if matches[4] == "[build failed]" {
+				// the build of the package failed, inject a dummy test into the package
+				// which indicate about the failure and contain the failure description.
+				pack.Tests = []*Test{
```
Comment (jstemmer) [inline parser/parser.go]: This works, but I'd prefer if you just add a new `Test` to the `tests` slice to keep it similar with what we do on line 90 for example.

File: parser/parser.go (hunk 6 above)
Comment (posener) [inline parser/parser.go]: I personally like that all the regexps are collected to a central place. I'll fix that.

File: parser/parser.go (hunk 7 above)
Comment (posener) [inline parser/parser.go]: Great idea, will fix

**Comment by posener** [comment]
Good catch @jstemmer , about the stderr piping. Thanks
Fixed CR comments and pushed changes.

File: parser/parser.go (hunk 6 above)
Comment (jstemmer) [inline parser/parser.go]: I understand, but this is a trivial check (similar to handling the `=== RUN ` line) where we don't need the complexity of a regular expression.

**Comment by jstemmer** [comment]
Looks good :+1: 

Thanks for contributing!

**Comment by MicahLC** [comment]
Thanks to both of you!
